
server:
  port: 8081

spring:
  application:
    name: pda-backend   #정보관리센터
  profiles:
    # active: prod
    active: dev
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB    


  
jwt:
  header: Authorization
  secret: densopda!@
  token:
    #1시간(60*60*1000)
    access-expire-time: '87400000'  #24시간

mybatis:
  configuration:
    jdbc-type-for-null: varchar   #쿼리에 보내는 파라미터가 null일경우 varchar로 인식시키기
    map-underscore-to-camel-case: true  #스네이크 표기법=> 카멜표기법으로 변경 (Map으로 받으면 인식안됨 dto로 받을경우만.)=> MAP은 javaBean이 아니라서
    call-setters-on-nulls: true   # select시 컬럼값이 null일경우 해당컬럼 포함여부( Map으로 반환받을경우 값이 null이면 해당필드 값이 없음.)

--- #개발 환경
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      maximum-pool-size: 10
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@database-1.cy8m9fkqr5u1.ap-northeast-2.rds.amazonaws.com:1521:ORCL
      username: admin
      password: kdata4706!!
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3600000  #1시간(60*60*1000)
            logger-level: full       #none,basic,headers,full
            read-timeout: 3600000    
file:
  dir: C:/temp/
  

--- #배포환경
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      maximum-pool-size: 10
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://newproject-test.cy8m9fkqr5u1.ap-northeast-2.rds.amazonaws.com:3306/kdatalab?&allowMultiQueries=true
      username: admin
      password: kdata4706!
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3600000
            logger-level: full       #none,basic,headers,full
            read-timeout: 3600000   

file:
  dir: /home/ubuntu/health/files/
